### ISSUE TITLE
Issues regarding running the code

### ISSUE THREAD

**Issue by robbiewyu** [Jaeyoung-Lim/px4-offboard#12]
Hello, thanks for posting this illuminating example! When I run it, the vehicle status (navigation mode) keeps on reverting to 4 (loiter mode) and not the desired 14. All the channels are getting published to though. I tried changing the gazebo parameters (param set COM_RCL_EXCEPT 4, param set NAV_DLL_ACT 0, and param set NAV_RCL_ACT 0) so that remote control loss wouldn't result in an automatic mode switch, but I haven't had any success. Wondering if there's anything setup-specific.

Thanks!

**Comment by Jaeyoung-Lim** [comment]
@robbiewyu It is most likely that your ros2 publications are not reaching PX4
