### ISSUE TITLE
Question regarding PX4 version

### ISSUE THREAD

**Issue by mamariomiamo** [Jaeyoung-Lim/px4-offboard#14]
Really appreciate the efforts from @stevehenderson to come up with the detailed setup tutorial.

I do have question regarding which PX4 version should we use alongside this package? The link in the tutorial seems to use the main branch.

**Comment by Jaeyoung-Lim** [comment]
@mamariomiamo Yes you should use main

**Comment by mamariomiamo** [comment]
> @mamariomiamo Yes you should use main

thanks!
