### ISSUE TITLE
uxrce dds pauses intermittently 

### ISSUE THREAD

**Issue by kyuhyong1** [Jaeyoung-Lim/px4-offboard#21]
PX4 6x is wire connected to a Offboard Controller(a small pc with ubuntu 18.04 and ros2 source installed) and then connected to Host PC via ethernet.
PX4 <-- /dev/ttyS3 --> Offboard Controller(Ubuntu 18.04 with ROS foxy) <----ethernet---> Host PC (Ubuntu 20.04 with ROS foxy installed)

uxrce_dds_client is start from PX4
`uxrce_dds_client start -t serial -d /dev/ttyS3 -b 921600`

UXRCEAgent is run from Offboard Controller
`MicroXRCEAgent serial -b 921600 --dev /dev/ttyHS1`

Offboard control is run from Host PC as below
`ros2 launch px4_offboard offboard_velocity_control.launch.py`

I was able to get updates from PX4 board however it pauses for a while then updates.
Below video capture shows what happens when dds stops.

https://youtu.be/mWgjA2rlyhw

Any idea about what is causing this issue?

**Comment by mavneo** [comment]
@kyuhyong1 the ros2 node you are running for keyboard based control seems to be from this example, better you ask there only, #https://github.com/ARK-Electronics/ROS2_PX4_Offboard_Example.git

**Comment by Jaeyoung-Lim** [comment]
@kyuhyong1 Any updates?

**Comment by kyuhyong1** [comment]
Hi @Jaeyoung-Lim 
We switched to different branch and working with it now. No issue with this now. 
Thanks!
