### ISSUE TITLE
fixed-wing offboard control

### ISSUE THREAD

**Issue by gspark87** [Jaeyoung-Lim/px4-offboard#22]
Hello,
I'm looking for fixed-wing offboard example on ROS2.

When I applied this code to the fixed wing, it doesn't work.
Should I use MAVLink(mavros) instead of ROS2 message(px4_msgs) in the fixed-wing offboard control?

**Comment by Jaeyoung-Lim** [comment]
> When I applied this code to the fixed wing, it doesn't work.

@gspark87 Could you elaborate on what "doesn't work" mean?

**Comment by gspark87** [comment]
@Jaeyoung-Lim Thank you for reply.
I modified it as below by referring to your code. It doesn't work as intended to fixed-wing(FW).
env) ubuntu 22.04 / ROS2 humble / PX4 1.15.0alpha

```
    def cmdloop_callback(self):
        # Publish offboard control modes
        if MODE == 'POS':
            offboard_msg = OffboardControlMode()
            offboard_msg.timestamp = int(Clock().now().nanoseconds / 1000)
            offboard_msg.position=True
            offboard_msg.velocity=False
            offboard_msg.acceleration=False
            self.publisher_offboard_mode.publish(offboard_msg)
            if self.nav_state == VehicleStatus.NAVIGATION_STATE_OFFBOARD:
                trajectory_msg = TrajectorySetpoint()
                trajectory_msg.position[0] = 100.0
                trajectory_msg.position[1] = 100.0
                trajectory_msg.position[2] = -60.0
                self.publisher_trajectory.publish(trajectory_msg)

        if MODE == 'ATT':
            offboard_msg = OffboardControlMode()
            offboard_msg.timestamp = int(Clock().now().nanoseconds / 1000)
            offboard_msg.position=False
            offboard_msg.velocity=False
            offboard_msg.acceleration=False
            offboard_msg.attitude=True
            self.publisher_offboard_mode.publish(offboard_msg)
            if self.nav_state == VehicleStatus.NAVIGATION_STATE_OFFBOARD:
                quat = navpy.angle2quat(45.0, -20.0, 30.0, input_unit='deg', rotation_sequence='ZYX')
                att_msg = VehicleAttitudeSetpoint()
                att_msg.q_d = [quat[0], quat[1][0], quat[1][1], quat[1][2]]
                att_msg.thrust_body = [0.6, 0.0, 0.0]
                self.publisher_attitude.publish(att_msg)
```

> Could you elaborate on what "doesn't work" mean?

**Problem**
1. In offboard position control, FW do not fly to position setpoint.
The type_mask(position) exist in MAVLink message, but not in px4_msgs.
![fw_offboard_position](https://github.com/Jaeyoung-Lim/px4-offboard/assets/52128149/e86acf7f-287c-4976-be41-7ea06b2d277b)
2. In offboard attitude control, FW does not maneuver to desired quaternion.
The trust_body command works and can also be seen that the thrust changes in QGC.
3. There is an offboard button in QGC of Multicopter, but not in fixedwing.
I changed the offboard mode using px4_msgs. Why offboard button doesn't find on FW in QGC?
`self.vehicle_command(VehicleCommand().VEHICLE_CMD_DO_SET_MODE, 1.0, 6.0)`
![qgc_offboard](https://github.com/Jaeyoung-Lim/px4-offboard/assets/52128149/5b2a2fa4-a4c0-43ea-91e6-69243af41f63)


> Either should work,

In PX4 User Guide, It seems like only Copter is available for ROS2 Messages such as `px4_msgs::msg::TrajectorySetpoint` and `px4_msgs::msg::VehicleAttitudeSetpoint`.
https://docs.px4.io/main/en/flight_modes/offboard.html

> if you are interested in creating a specific example, I would be interested in collaborating.

When the probelm is resolved, I will share it.

**Comment by Jaeyoung-Lim** [comment]
@gspark87 The current implementation for fixedwing offboard trajectory following requires you to provide the velocity setpoints, which interprets it as ground speed.

To use position-only setpoints for offboard mode, you can use https://github.com/PX4/PX4-Autopilot/pull/21376

**Comment by gspark87** [comment]
> Note that you additionally need to populate the velocity setpoints with nan values for it to get ignored, since the messages from python get initialized as zeros(which are valid).

Fixedwing offboard position control was solved immediately by velocity setpoints with `nan`.
```
trajectory_msg = TrajectorySetpoint()
trajectory_msg.position[0] = -100.0      # North
trajectory_msg.position[1] = -100.0      # East
trajectory_msg.position[2] = -60.0        # Down
trajectory_msg.velocity[0] = math.nan   # solved
trajectory_msg.velocity[1] = math.nan
trajectory_msg.velocity[2] = math.nan
self.publisher_trajectory.publish(trajectory_msg)
```
<br/>

> Have you tried setting the body relative euler angles?

As you advised, I used body angle `roll_body`, `pitch_body` instead of quaternion `q_d`, so it was solved.
But, `yaw_body` is not working.

<br/>

> This seems like a bug in QGC that might be worth raising.
You can also simply type commander mode offboard in the px4 shell if you are running SITL

 Thanks for letting me know.

**Comment by Jaeyoung-Lim** [comment]
> But, yaw_body is not working.

@gspark87 You might want to raise this directly in the PX4 repository, since this is more related to the flight control side, rather than this repository.

**Comment by gspark87** [comment]
@Jaeyoung-Lim Happy new year!

> May I ask you what you are trying to do with just position and attitude references?

I am trying to fly autonomously with reinforcement learning.
I was testing setpoint interfaces one by one, considering the communication of RL agent and PX4.
![offboard](https://github.com/Jaeyoung-Lim/px4-offboard/assets/52128149/c76cfa75-f283-4b34-bb5a-241fb52a5050)

**Comment by gspark87** [comment]
Here is the code I tested.
https://github.com/gspark87/px4_offboard/

**Comment by Jaeyoung-Lim** [comment]
@gspark87 It appears you have made a copy of the code in this repository and removed the licenses. Could you explain why you have removed the license headers?

**Comment by gspark87** [comment]
@Jaeyoung-Lim 
I'm sorry, added the license in this code.
Is it okay if I do this?
