### ISSUE TITLE
No reaction to launching the demo

### ISSUE THREAD

**Issue by felix-muller** [Jaeyoung-Lim/px4-offboard#25]
Hi! I was going through the tutorial and everything was working as described until the last step. 

After launching the demo, I switched to offboard mode in QGC, but nothing happened after waiting for a few seconds. The visualizer and control nodes are running and RViz opened, but nothing is getting published to /fmu/in/trajectory_setpoint.

Thank you!

**Comment by felix-muller** [comment]
My mistake was using PX4-Autopilot and px4_msgs on different versions. Here is what I found:

- PX4-Autopilot in release/1.14 and px4_msgs in main produces the problem described above (obvious in hindsight)
- PX4-Autopilot in release/1.14 and px4_msgs in release/1.14 makes it impossible to switch to offboard mode (no offboard signal)
- PX4-Autopilot in main and px4_msgs in main works

**Comment by Jaeyoung-Lim** [comment]
@felix-muller Great! Thanks for the update!

**Comment by Jimi1811** [comment]
Hello! @felix-muller have you tried in a companion like Jetson? I found in Discord community that there are problems with the communication with the Autopilot using the main branch.

**Comment by Jaeyoung-Lim** [comment]
@Jimi1811 I dont think there is a known issue with using micro-ros with the fmu between the jetson.

I used micro-ros and it works

**Comment by Jaeyoung-Lim** [comment]
Closing as this issue seems stale. Please reopen if you think this is still relevant
