### ISSUE TITLE
Getting a message type px4_msgs/msg/VehicleStatus is invalid error when trying to echo the topic

### ISSUE THREAD

**Issue by maverickk9** [Jaeyoung-Lim/px4-offboard#26]
I am following this tutorial doc: https://github.com/Jaeyoung-Lim/px4-offboard/blob/master/doc/ROS2_PX4_Offboard_Tutorial.md

**Comment by Jaeyoung-Lim** [comment]
@maverickk9 Please provide details of what the problem you are struggling with. The tutorial should work out of the box, and it is hard to help with limited information.

**Comment by Jaeyoung-Lim** [comment]
Closing as there was no response. Feel free to reopen if you think this is still relevant
