### ISSUE TITLE
[Feature idea] Automatic path clearing upon simulation reset

### ISSUE THREAD

**Issue by rosiakpiotr** [Jaeyoung-Lim/px4-offboard#28]
Hello, first of all thank you for providing the code for path visualization of PX4 SITL using RVIZ2. I've been using it and found that a nice feature would be to reset already existing path whenever simulation is killed and started again without the necessity to re-run visualization node. Currently last point is connected to the spawn point rendering glitchy outcome (the old path is also there if we don't wait for it to disappear by being replaced with new one). I added clearing by the time difference between last message implemented inside local position callback function (linked below) https://github.com/Jaeyoung-Lim/px4-offboard/blob/1c4f330747d545cc966d1cd4929c630ecc39a685/px4_offboard/visualizer.py#L131

In the node initialization (`__init__`) we can have initialization of last timestamp variable such as
```python
self.last_update = 0
``` 

And then inside the callback
```python
if (Clock().now().nanoseconds / 1e6 - self.last_update) > 1000:
      self.get_logger().warning(
          f"Time since last update: {Clock().now().nanoseconds / 1e6 - self.last_update}"
      )
      self.get_logger().info("Resetting path history")
      self.vehicle_path_msg.poses.clear()
```

Where `1000` is the time in milliseconds that represents maximum time difference between new local position updates (effectively triggering upon new simulation start). Logging can be dropped of course.

**Comment by Jaeyoung-Lim** [comment]
@rosiakpiotr I am not sure if I fully get what the problem you are solving.

If you make a PR I will be happy to review it
