### ISSUE TITLE
Offboard velocity control

### ISSUE THREAD

**Issue by E-Olcay** [Jaeyoung-Lim/px4-offboard#6]
I've been working for a couple weeks  on tracking of  reference velocities (only v_x, v_y, v_z) using Offboard node. Although I checked the example implementation here and some other examples written with cpp, I don't have success. A very interesting thing is that the reference velocity in z direction is tracked well. However, according to the flight review, v_x and v_y are even not received by PX4 although I publish them in the same way as v_z.  I should mention that we don't use the updated version of PX4 autopilot and micrortps. I attached a log file. Someone can maybe see what I overlook. I can also post my implementation if it's required.
[PX4logs.zip](https://github.com/Jaeyoung-Lim/px4-offboard/files/9982991/PX4logs.zip)

**Comment by Jaeyoung-Lim** [comment]
> However, according to the flight review, v_x and v_y are even not received by PX4 although I publish them in the same way as v_z. 

![image](https://user-images.githubusercontent.com/5248102/201164491-80381b30-37cb-4d28-ba21-6d9a07153cb2.png)
![image](https://user-images.githubusercontent.com/5248102/201164791-1cd46813-4ad0-44ae-9d72-dd290becc487.png)

I think there is something wrong in the implementation of how you publish vx and vy

**Comment by E-Olcay** [comment]
v_x and v_y are published via TrajectorySetpoint (px4_msgs.msg -> float32 vx, float32 vy, float32 vz). An example reference velocity is e.g.; [5.0, 0.0, 0.0]
In OffboardControlMode, I set msg. velocity to True and the rest to False.  In TrajectorySetpoint(), msg.x, msg.y, and msg.z are all set to float("NaN") in offboard node.
After the agent reaches an altitude of 7m with 3m/s, all velocities are set to zero and Offboard control is activated.

**Comment by Jaeyoung-Lim** [comment]
@E-Olcay How are you sending the setpoints? Are you using the microdds bridge? Why is vz set properly and not vx and vy?

**Comment by Jaeyoung-Lim** [comment]
If you are using the microRTPS bridge, I would check the message definitions if they are compatible. The microRTPS has been removed from PX4 now, so better to transition to the microdds
